/// <reference types="nativewind/types" />

// NOTE: This file should not be edited and should be committed with your source code. It is generated by NativeWind.
declare module "*.png" {
  const value: any;
  export default value;
}
